In [10]:
# Import
import pandas as pd
import numpy as np
import hvplot.pandas
from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()
import csv
from binance import Client
import path
# Setting these options will allow for reviewing more of the DataFrames
pd.set_option('display.max_rows', 2000)
pd.set_option('display.max_columns', 2000)
pd.set_option('display.width', 1000)

In [14]:
API_KEY = os.getenv('API_KEY')
API_SECRET = os.getenv('API_SECRET')

client = Client(API_KEY, API_SECRET)

csvfile= open('doge1.csv','w', newline='')

candlestick_writer = csv.writer(csvfile, delimiter=',')

candlesticks = client.get_historical_klines("DOGEUSDT", Client.KLINE_INTERVAL_1HOUR, "1 jan 2019", "5 jan 2022")

for candlestick in candlesticks:
    candlestick[0] = candlestick[0] / 1000
    candlestick_writer.writerow(candlestick)

In [15]:
csvfile.close()

In [8]:
# CSV file coverter

data= pd.read_csv(
Path("./doge1h.csv"))
data = data.iloc[:,[1,2,3,4,5]]
data.columns =(['Open','High','Low','Close','Volume'])

date = pd.date_range(start='1/JAN/2019', end='5/JAN/2022', freq='1H')
date = pd.DataFrame(date)
data = data.assign(Date=date)
data.set_index(['Date'],inplace = True)
data.tail(10)

                       Open    High     Low   Close      Volume
Date
2021-07-01 08:00:00  0.1720  0.1726  0.1706  0.1710  22733987.0
2021-07-01 09:00:00  0.1710  0.1712  0.1702  0.1707  24341119.0
2021-07-01 10:00:00  0.1707  0.1720  0.1702  0.1702  15326283.0
2021-07-01 11:00:00  0.1703  0.1707  0.1665  0.1677  53667689.0
2021-07-01 12:00:00  0.1677  0.1692  0.1668  0.1684  34058231.0
2021-07-01 13:00:00  0.1685  0.1695  0.1680  0.1692  16706908.0
2021-07-01 14:00:00  0.1692  0.1696  0.1687  0.1691  17197978.0
2021-07-01 15:00:00  0.1690  0.1696  0.1684  0.1692  16450100.0
2021-07-01 16:00:00  0.1692  0.1693  0.1679  0.1684  12601198.0
2021-07-01 17:00:00  0.1685  0.1695  0.1677  0.1693  16958607.0

In [9]:
data.to_csv('DOGEUSDT1H.csv')